version: '3.8'

services:

  rabbitmq:
    image: bitnami/rabbitmq:latest
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_PASSWORD=my_password
    networks:
      - app-tier

networks:
  app-tier:
